name: youonline
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rename: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^5.0.0
  google_fonts: 
  textfield_tags: ^1.1.1
  flutter_snake_navigationbar: ^0.5.0
  dotted_decoration: ^2.0.0
  http: 
  shared_preferences: 
  bot_toast: ^4.0.1
  file_picker: 
  universal_html: any
  youtube_player_flutter: ^8.0.0
  audioplayers: ^0.19.0
  expandable: ^5.0.1
  pin_code_fields: ^7.0.0
  flutter_swiper: ^1.1.6
  video_player: 
  pull_to_refresh: ^2.0.0
  flutter_uploader: ^1.2.1
  async:
  image_picker: 
  flutter_story_list: ^1.0.4
  story: ^0.5.1
  transparent_image: ^2.0.0
  chewie: any
  cached_network_image: ^3.0.0
  loading_indicator: 
  flutter_datetime_picker: ^1.5.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/sounds/share.mp3